/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tic.toe;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        //
    }

    public static void main(String[] args) {
        launch();
    }

}
